### ISSUE TITLE
No support for Red Hat platform

### ISSUE THREAD

**Issue by akulbe** [hoeggsoftware/mule-cookbook#20]
It would be nice to get support for this cookbook on RHEL.
I'm trying to get it automated on RHEL 7.2 / 7.3.

Thank you for your work!!

**Comment by rhoegg** [comment]
This seems to work on CentOS, will you try it on RHEL? #21

**Comment by rhoegg** [comment]
It's released to the supermarket in 0.7.0

**Comment by claytonflesher** [comment]
Going to close this one since it's in the supermarket.
