### ISSUE TITLE
Chef >= 13.0 support

### ISSUE THREAD

**Issue by PierreBeucher** [hoeggsoftware/mule-cookbook#23]
As of Chef 13.0, some features have been deprecated and this cookbook does not work on Chef >=13.0.

Some of the issues encountered: 

[default values for resource properties are frozen](https://docs.chef.io/release_notes.html#default-values-for-resource-properties-are-frozen), resulting in errors such as:

           Error executing action `create` on resource 'mule_debian[mule-standalone]'

           RuntimeError
           ------------
           can't modify frozen Array

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/mule/resources/debian.rb:132:in `push'
           /tmp/kitchen/cache/cookbooks/mule/resources/debian.rb:132:in `update_wrapper'
           /tmp/kitchen/cache/cookbooks/mule/resources/debian.rb:37:in `block in class_from_file'

I am currently working on a fork to adapt this cookbook for Chef 13, and will create a pull request if this repo is still maintained :) I'll try to keep Chef 12 support as well.

**Comment by rhoegg** [comment]
Great find, thanks! Yes please send a PR

**Comment by claytonflesher** [comment]
Closing after merge.
